In [ ]:
# 데이터분석 패키지 준비
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: openpyxl in c:\users\human\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\human\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install openpyxl

In [118]:
paths = "../data-files/seoul-cctv.xlsx"

cctv = pd.read_excel(paths, skiprows=2)

In [119]:

print(cctv.info())
print(cctv.shape)
print(cctv.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          0 non-null      float64
 1   순번                  26 non-null     object
 2   구분                  26 non-null     object
 3   총 계                 26 non-null     float64
 4   2015년 이전 설치된 CCTV   26 non-null     float64
 5   2016년               26 non-null     float64
 6   2017년               26 non-null     float64
 7   2018년               26 non-null     float64
 8   2019년               26 non-null     float64
 9   2020년               26 non-null     float64
 10  2021년               26 non-null     float64
 11  2022년               26 non-null     float64
 12  2023년               26 non-null     float64
 13  2024년               26 non-null     float64
dtypes: float64(12), object(2)
memory usage: 3.1+ KB
None
(27, 14)
   Unnamed: 0   순번   구분       총 계  2015년 이전 설치된 CCTV    2016년    2017년  \
0         NaN  NaN    계  113273.0              9702.0  8827.0  10108.0
1         NaN    1  종로구    2339.0               146.0    76.0    115.0
2         NaN    2  중 구    3118.0               356.0   219.0    366.0
3         NaN    3  용산구    3609.0                24.0   124.0    454.0
4         NaN    4  성동구    4638.0              1295.0   228.0    881.0

     2018년    2019년    2020년   2021년   2022년    2023년    2024년
0  10594.0  12562.0  11865.0  9358.0  9397.0  13857.0  17003.0
1    137.0     68.0    231.0    86.0   234.0    924.0    322.0
2    385.0    159.0    352.0   416.0   137.0    135.0    593.0
3    119.0    335.0    625.0   431.0   457.0    411.0    629.0
4    383.0    477.0    386.0   294.0   170.0    320.0    204.0

In [131]:
# 데이터 다듬기

# 복사본 생성
seoul_cctv = cctv.copy()

# 행과 열 제거
seoul_cctv.drop([0,26], axis=0, inplace=True) # inplace=True 원본 삭제
seoul_cctv.drop(cctv.columns[:2], axis=1, inplace=True)
seoul_cctv.reset_index(drop=True, inplace=True) # 인덱스 초기화 

# 컬럼명 변경
seoul_cctv.rename(columns={ "구분":"자치구"}, inplace=True)
seoul_cctv.rename(columns={ "총 계":"총계"}, inplace=True)
seoul_cctv.rename(columns={ seoul_cctv.columns[2]:"2015년_이하"}, inplace=True) 

print(seoul_cctv.info())
print(seoul_cctv.shape)
print(seoul_cctv.head())
seoul_cctv.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   자치구       25 non-null     object
 1   총계        25 non-null     float64
 2   2015년_이하  25 non-null     float64
 3   2016년     25 non-null     float64
 4   2017년     25 non-null     float64
 5   2018년     25 non-null     float64
 6   2019년     25 non-null     float64
 7   2020년     25 non-null     float64
 8   2021년     25 non-null     float64
 9   2022년     25 non-null     float64
 10  2023년     25 non-null     float64
 11  2024년     25 non-null     float64
dtypes: float64(11), object(1)
memory usage: 2.5+ KB
None
(25, 12)
   자치구      총계  2015년_이하  2016년  2017년  2018년  2019년  2020년  2021년  2022년  \
0  종로구  2339.0     146.0   76.0  115.0  137.0   68.0  231.0   86.0  234.0
1  중 구  3118.0     356.0  219.0  366.0  385.0  159.0  352.0  416.0  137.0
2  용산구  3609.0      24.0  124.0  454.0  119.0  335.0  625.0  431.0  457.0
3  성동구  4638.0    1295.0  228.0  881.0  383.0  477.0  386.0  294.0  170.0
4  광진구  4636.0     247.0   38.0  660.0  465.0  710.0  194.0  744.0  276.0

   2023년  2024년
0  924.0  322.0
1  135.0  593.0
2  411.0  629.0
3  320.0  204.0
4  348.0  954.0

,자치구,총계,2015년_이하,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년,2024년
0,종로구,2339.0,146.0,76.0,115.0,137.0,68.0,231.0,86.0,234.0,924.0,322.0
1,중 구,3118.0,356.0,219.0,366.0,385.0,159.0,352.0,416.0,137.0,135.0,593.0
2,용산구,3609.0,24.0,124.0,454.0,119.0,335.0,625.0,431.0,457.0,411.0,629.0
3,성동구,4638.0,1295.0,228.0,881.0,383.0,477.0,386.0,294.0,170.0,320.0,204.0
4,광진구,4636.0,247.0,38.0,660.0,465.0,710.0,194.0,744.0,276.0,348.0,954.0